[build]
  base = "/"
  command = "npm run build"
  publish = "/dist/"
  [build.environment]
    NODE_VERSION = "18"

[functions]
  directory = "src/functions"
  node_bundler = "esbuild"
  external_node_modules = ["express", "mongoose", "cors", "dotenv"]
