[build]
  base = "/"
  command = "npm run build"
  publish = "/dist/"
  [build.environment]
    NODE_VERSION = "18"
[functions]
  external_node_modules = ["express", "mongodb"]
  node_bundler = "esbuild"